### ISSUE TITLE
Display issue with 5th line blocks in level

### ISSUE THREAD

**Issue by nadeem-114** [DG-Apps-Studio/words-game#13]
**Description:**
In Level # 153 (Or any level with 5 lines of blocks), when attempting to unscramble five words, the blocks displayed in the 5th line are improperly rendered. The upper part of the blocks in the 5th line is cut off slightly, resulting in an incomplete and visually unappealing display.

**Steps to Reproduce:**
1. Launch the game and navigate to Level # 153 (Or any level with 5 lines of blocks).
2. Observe the arrangement of blocks in the 5th line while attempting to unscramble five words.

**Expected Behaviour:**
In Level # 153 (Or any level with 5 lines of blocks), the blocks in the 5th line should be rendered correctly, fully visible, and aligned with the blocks in the other lines. The complete circle of blocks should be displayed without any cut-off or misalignment.

**Actual Behaviour:**
Upon reaching Level # 153 (Or any level with 5 lines of blocks) and attempting to unscramble five words, the blocks in the 5th line are not displayed properly. The upper part of the blocks is cut off slightly, causing an incomplete appearance compared to the other lines of blocks.

![MicrosoftTeams-image (2)](https://github.com/DG-Apps-Studio/words-game/assets/33491661/312a826b-f7b0-4692-9ea6-998354d0432e)

**Comment by Ehtisham-gillani** [comment]
https://we.tl/t-q9Q9adfzDe
Issue Resolved

**Comment by nadeem-114** [comment]
Tested - **Passed**
