### ISSUE TITLE
Lack of vibration for correct but previously unscrambled words

### ISSUE THREAD

**Issue by nadeem-114** [DG-Apps-Studio/words-game#15]
**Description:**
In the Word Puzzle game, when a user successfully unscrambles a correct word that has already been unscrambled in the current level, the game does not trigger a vibration as intended. However, vibrations are correctly generated for incorrect word attempts, leading to inconsistent feedback for the player.

**Steps to Reproduce:**
1. Launch the game and navigate to a level that contains a word previously unscrambled.
2. Attempt to unscramble the correct word that has already been unscrambled in the same level.

**Expected Behaviour:**
When the user unscrambles a word correctly, regardless of whether it has been unscrambled before in the same level, the game should provide consistent feedback, including a vibration to indicate a correct word formation.

**Actual Behaviour:**
When a user successfully unscrambles a correct word that has already been unscrambled in the current level, the game fails to generate a vibration, resulting in inconsistent feedback. However, vibrations are appropriately triggered for incorrect word attempts.

**Comment by Ehtisham-gillani** [comment]
https://we.tl/t-I1Xq6QyGSk

**Comment by nadeem-114** [comment]
Tested - **Passed**
