### ISSUE TITLE
App crash on "Play" Button after 200 levels

### ISSUE THREAD

**Issue by nadeem-114** [DG-Apps-Studio/words-game#19]
**Description:**
After completing all 200 levels in the Word Puzzle game, clicking the "Play" button in the congrats popup results in a crash. This crash occurs because there are no more levels to progress to, and the app is unable to handle this scenario gracefully.

**Steps to Reproduce:**
1. Play through all 200 levels of the game.
2. Upon completing the final level, observe the congrats popup with the "Play Again" and "Play Next" buttons.
3. Click the "Play Next" button in the congrats popup.

**Expected Behaviour:**
When the "Play Next" button is clicked after completing all levels, the app should provide a meaningful response, such as displaying a message indicating that there are no more levels to play.

**Actual Behaviour:**
Clicking the "Play Next" button after completing all levels leads to an app crash. The app is unable to handle this scenario and abruptly terminates.

**Comment by Ehtisham-gillani** [comment]
https://we.tl/t-2Hi71PF2hH
Issue Solved

**Comment by nadeem-114** [comment]
Tested - **Passed**
